### ISSUE TITLE
Wrong elevation is returned in 3D view in groundAlt example

### ISSUE THREAD

**Issue by tlpinney** [AnalyticalGraphicsInc/cesium-google-earth-examples#61]
It is returning around -10,000 meters for certain areas in the United States. 
![screen shot 2015-02-13 at 2 41 34 pm](https://cloud.githubusercontent.com/assets/152429/6194039/8076af04-b38e-11e4-872e-1292bda0010e.png)

**Comment by pjcozzi** [comment]
Like Google Earth, it gets more precise as you zoom in.  We plan to improve this.  See https://groups.google.com/forum/#!topic/cesium-dev/piux2QQqo3k
